name: TV Card
description: Apple TV Remote Card
type: lovelace
keywords:
  - tvcard
  - apple
  - remote
  - tv
  - television
author:
  name: jpn2
license: Apache License, Version 2.0
files:
  - tv-card.js